"""empty message

Revision ID: 18dfdfa02a49
Revises: 9d9db9f64cde
Create Date: 2024-08-04 23:15:07.744497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18dfdfa02a49"
down_revision: Union[str, None] = "9d9db9f64cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "board", sa.Column("update_date", sa.TIMESTAMP(timezone=True), nullable=False)
    )
    op.add_column(
        "post", sa.Column("update_date", sa.TIMESTAMP(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "update_date")
    op.drop_column("board", "update_date")
    # ### end Alembic commands ###
