"""empty message

Revision ID: c4dd07b87ca8
Revises: 71c5b2c8223c
Create Date: 2024-08-03 21:46:46.510808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4dd07b87ca8"
down_revision: Union[str, None] = "71c5b2c8223c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("board_user_id_fkey", "board", type_="foreignkey")
    op.create_foreign_key(
        None, "board", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("post_user_id_fkey", "post", type_="foreignkey")
    op.drop_constraint("post_board_id_fkey", "post", type_="foreignkey")
    op.create_foreign_key(
        None, "post", "board", ["board_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "post", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.alter_column(
        "user", "full_name", existing_type=sa.VARCHAR(length=30), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "full_name", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    op.drop_constraint(None, "post", type_="foreignkey")
    op.drop_constraint(None, "post", type_="foreignkey")
    op.create_foreign_key("post_board_id_fkey", "post", "board", ["board_id"], ["id"])
    op.create_foreign_key("post_user_id_fkey", "post", "user", ["user_id"], ["id"])
    op.drop_constraint(None, "board", type_="foreignkey")
    op.create_foreign_key("board_user_id_fkey", "board", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
